package com.finflow.dto.response;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class ResponseDTOs {
    public static class AuthResponse {
        private String token, tokenType, fullName, email, role; private Long userId;
        public String getToken(){return token;} public void setToken(String v){token=v;} public String getTokenType(){return tokenType;} public void setTokenType(String v){tokenType=v;} public Long getUserId(){return userId;} public void setUserId(Long v){userId=v;} public String getFullName(){return fullName;} public void setFullName(String v){fullName=v;} public String getEmail(){return email;} public void setEmail(String v){email=v;} public String getRole(){return role;} public void setRole(String v){role=v;}
        public static Builder builder(){return new Builder();} public static class Builder {private final AuthResponse x=new AuthResponse(); public Builder token(String v){x.token=v;return this;} public Builder tokenType(String v){x.tokenType=v;return this;} public Builder userId(Long v){x.userId=v;return this;} public Builder fullName(String v){x.fullName=v;return this;} public Builder email(String v){x.email=v;return this;} public Builder role(String v){x.role=v;return this;} public AuthResponse build(){return x;}}
    }
    public static class UserResponse {
        private Long id; private String fullName,email,role; private boolean enabled; private LocalDateTime createdAt;
        public Long getId(){return id;} public void setId(Long v){id=v;} public String getFullName(){return fullName;} public void setFullName(String v){fullName=v;} public String getEmail(){return email;} public void setEmail(String v){email=v;} public String getRole(){return role;} public void setRole(String v){role=v;} public boolean isEnabled(){return enabled;} public void setEnabled(boolean v){enabled=v;} public LocalDateTime getCreatedAt(){return createdAt;} public void setCreatedAt(LocalDateTime v){createdAt=v;}
        public static Builder builder(){return new Builder();} public static class Builder {private final UserResponse x=new UserResponse(); public Builder id(Long v){x.id=v;return this;} public Builder fullName(String v){x.fullName=v;return this;} public Builder email(String v){x.email=v;return this;} public Builder role(String v){x.role=v;return this;} public Builder enabled(boolean v){x.enabled=v;return this;} public Builder createdAt(LocalDateTime v){x.createdAt=v;return this;} public UserResponse build(){return x;}}
    }
    public static class AccountResponse {
        private Long id,userId; private String accountNumber,accountType,currency,status,ownerName; private BigDecimal balance; private LocalDateTime createdAt;
        public Long getId(){return id;} public void setId(Long v){id=v;} public String getAccountNumber(){return accountNumber;} public void setAccountNumber(String v){accountNumber=v;} public String getAccountType(){return accountType;} public void setAccountType(String v){accountType=v;} public BigDecimal getBalance(){return balance;} public void setBalance(BigDecimal v){balance=v;} public String getCurrency(){return currency;} public void setCurrency(String v){currency=v;} public String getStatus(){return status;} public void setStatus(String v){status=v;} public Long getUserId(){return userId;} public void setUserId(Long v){userId=v;} public String getOwnerName(){return ownerName;} public void setOwnerName(String v){ownerName=v;} public LocalDateTime getCreatedAt(){return createdAt;} public void setCreatedAt(LocalDateTime v){createdAt=v;}
        public static Builder builder(){return new Builder();} public static class Builder {private final AccountResponse x=new AccountResponse(); public Builder id(Long v){x.id=v;return this;} public Builder accountNumber(String v){x.accountNumber=v;return this;} public Builder accountType(String v){x.accountType=v;return this;} public Builder balance(BigDecimal v){x.balance=v;return this;} public Builder currency(String v){x.currency=v;return this;} public Builder status(String v){x.status=v;return this;} public Builder userId(Long v){x.userId=v;return this;} public Builder ownerName(String v){x.ownerName=v;return this;} public Builder createdAt(LocalDateTime v){x.createdAt=v;return this;} public AccountResponse build(){return x;}}
    }
    public static class TransactionResponse {
        private Long id; private String referenceNumber,transactionType,currency,sourceAccountNumber,destinationAccountNumber,senderName,recipientName,status,description,remarks; private BigDecimal amount; private LocalDateTime processedAt,createdAt;
        public Long getId(){return id;} public void setId(Long v){id=v;} public String getReferenceNumber(){return referenceNumber;} public void setReferenceNumber(String v){referenceNumber=v;} public String getTransactionType(){return transactionType;} public void setTransactionType(String v){transactionType=v;} public BigDecimal getAmount(){return amount;} public void setAmount(BigDecimal v){amount=v;} public String getCurrency(){return currency;} public void setCurrency(String v){currency=v;} public String getSourceAccountNumber(){return sourceAccountNumber;} public void setSourceAccountNumber(String v){sourceAccountNumber=v;} public String getDestinationAccountNumber(){return destinationAccountNumber;} public void setDestinationAccountNumber(String v){destinationAccountNumber=v;} public String getSenderName(){return senderName;} public void setSenderName(String v){senderName=v;} public String getRecipientName(){return recipientName;} public void setRecipientName(String v){recipientName=v;} public String getStatus(){return status;} public void setStatus(String v){status=v;} public String getDescription(){return description;} public void setDescription(String v){description=v;} public String getRemarks(){return remarks;} public void setRemarks(String v){remarks=v;} public LocalDateTime getProcessedAt(){return processedAt;} public void setProcessedAt(LocalDateTime v){processedAt=v;} public LocalDateTime getCreatedAt(){return createdAt;} public void setCreatedAt(LocalDateTime v){createdAt=v;}
        public static Builder builder(){return new Builder();} public static class Builder {private final TransactionResponse x=new TransactionResponse(); public Builder id(Long v){x.id=v;return this;} public Builder referenceNumber(String v){x.referenceNumber=v;return this;} public Builder transactionType(String v){x.transactionType=v;return this;} public Builder amount(BigDecimal v){x.amount=v;return this;} public Builder currency(String v){x.currency=v;return this;} public Builder sourceAccountNumber(String v){x.sourceAccountNumber=v;return this;} public Builder destinationAccountNumber(String v){x.destinationAccountNumber=v;return this;} public Builder senderName(String v){x.senderName=v;return this;} public Builder recipientName(String v){x.recipientName=v;return this;} public Builder status(String v){x.status=v;return this;} public Builder description(String v){x.description=v;return this;} public Builder remarks(String v){x.remarks=v;return this;} public Builder processedAt(LocalDateTime v){x.processedAt=v;return this;} public Builder createdAt(LocalDateTime v){x.createdAt=v;return this;} public TransactionResponse build(){return x;}}
    }
    public static class AccountSummary {
        private Long accountId; private String accountNumber; private BigDecimal balance,totalCredits,totalDebits; private long totalTransactions; private LocalDateTime from,to;
        public Long getAccountId(){return accountId;} public void setAccountId(Long v){accountId=v;} public String getAccountNumber(){return accountNumber;} public void setAccountNumber(String v){accountNumber=v;} public BigDecimal getBalance(){return balance;} public void setBalance(BigDecimal v){balance=v;} public BigDecimal getTotalCredits(){return totalCredits;} public void setTotalCredits(BigDecimal v){totalCredits=v;} public BigDecimal getTotalDebits(){return totalDebits;} public void setTotalDebits(BigDecimal v){totalDebits=v;} public long getTotalTransactions(){return totalTransactions;} public void setTotalTransactions(long v){totalTransactions=v;} public LocalDateTime getFrom(){return from;} public void setFrom(LocalDateTime v){from=v;} public LocalDateTime getTo(){return to;} public void setTo(LocalDateTime v){to=v;}
        public static Builder builder(){return new Builder();} public static class Builder {private final AccountSummary x=new AccountSummary(); public Builder accountId(Long v){x.accountId=v;return this;} public Builder accountNumber(String v){x.accountNumber=v;return this;} public Builder balance(BigDecimal v){x.balance=v;return this;} public Builder totalCredits(BigDecimal v){x.totalCredits=v;return this;} public Builder totalDebits(BigDecimal v){x.totalDebits=v;return this;} public Builder totalTransactions(long v){x.totalTransactions=v;return this;} public Builder from(LocalDateTime v){x.from=v;return this;} public Builder to(LocalDateTime v){x.to=v;return this;} public AccountSummary build(){return x;}}
    }
}
